export const ALL_CATEGORYONES_REQUEST = 'ALL_CATEGORYONES_REQUEST'
export const ALL_CATEGORYONES_SUCCESS = 'ALL_CATEGORYONES_SUCCESS'
export const ALL_CATEGORYONES_FAIL = 'ALL_CATEGORYONES_FAIL'

export const CATEGORYONE_DETAILS_REQUEST = 'CATEGORYONE_DETAILS_REQUEST'
export const CATEGORYONE_DETAILS_SUCCESS = 'CATEGORYONE_DETAILS_SUCCESS'
export const CATEGORYONE_DETAILS_FAIL = 'CATEGORYONE_DETAILS_FAIL'

export const NEW_CATEGORYONE_REQUEST = 'NEW_CATEGORYONE_REQUEST'
export const NEW_CATEGORYONE_SUCCESS = 'NEW_CATEGORYONE_SUCCESS'
export const NEW_CATEGORYONE_RESET = 'NEW_CATEGORYONE_RESET'
export const NEW_CATEGORYONE_FAIL = 'NEW_CATEGORYONE_FAIL'

export const UPDATE_CATEGORYONE_REQUEST = 'UPDATE_CATEGORYONE_REQUEST'
export const UPDATE_CATEGORYONE_SUCCESS = 'UPDATE_CATEGORYONE_SUCCESS'
export const UPDATE_CATEGORYONE_RESET = 'UPDATE_CATEGORYONE_RESET'
export const UPDATE_CATEGORYONE_FAIL = 'UPDATE_CATEGORYONE_FAIL'

export const DELETE_CATEGORYONE_REQUEST = 'DELETE_CATEGORYONE_REQUEST'
export const DELETE_CATEGORYONE_SUCCESS = 'DELETE_CATEGORYONE_SUCCESS'
export const DELETE_CATEGORYONE_RESET = 'DELETE_CATEGORYONE_RESET'
export const DELETE_CATEGORYONE_FAIL = 'DELETE_CATEGORYONE_FAIL'

export const ALL_CATEGORYTWOS_REQUEST = 'ALL_CATEGORYTWOS_REQUEST'
export const ALL_CATEGORYTWOS_SUCCESS = 'ALL_CATEGORYTWOS_SUCCESS'
export const ALL_CATEGORYTWOS_FAIL = 'ALL_CATEGORYTWOS_FAIL'

export const CATEGORYTWO_DETAILS_REQUEST = 'CATEGORYTWO_DETAILS_REQUEST'
export const CATEGORYTWO_DETAILS_SUCCESS = 'CATEGORYTWO_DETAILS_SUCCESS'
export const CATEGORYTWO_DETAILS_FAIL = 'CATEGORYTWO_DETAILS_FAIL'

export const NEW_CATEGORYTWO_REQUEST = 'NEW_CATEGORYTWO_REQUEST'
export const NEW_CATEGORYTWO_SUCCESS = 'NEW_CATEGORYTWO_SUCCESS'
export const NEW_CATEGORYTWO_RESET = 'NEW_CATEGORYTWO_RESET'
export const NEW_CATEGORYTWO_FAIL = 'NEW_CATEGORYTWO_FAIL'

export const UPDATE_CATEGORYTWO_REQUEST = 'UPDATE_CATEGORYTWO_REQUEST'
export const UPDATE_CATEGORYTWO_SUCCESS = 'UPDATE_CATEGORYTWO_SUCCESS'
export const UPDATE_CATEGORYTWO_RESET = 'UPDATE_CATEGORYTWO_RESET'
export const UPDATE_CATEGORYTWO_FAIL = 'UPDATE_CATEGORYTWO_FAIL'

export const DELETE_CATEGORYTWO_REQUEST = 'DELETE_CATEGORYTWO_REQUEST'
export const DELETE_CATEGORYTWO_SUCCESS = 'DELETE_CATEGORYTWO_SUCCESS'
export const DELETE_CATEGORYTWO_RESET = 'DELETE_CATEGORYTWO_RESET'
export const DELETE_CATEGORYTWO_FAIL = 'DELETE_CATEGORYTWO_FAIL'

export const ALL_CATEGORYTHREES_REQUEST = 'ALL_CATEGORYTHREES_REQUEST'
export const ALL_CATEGORYTHREES_SUCCESS = 'ALL_CATEGORYTHREES_SUCCESS'
export const ALL_CATEGORYTHREES_FAIL = 'ALL_CATEGORYTHREES_FAIL'

export const CATEGORYTHREE_DETAILS_REQUEST = 'CATEGORYTHREE_DETAILS_REQUEST'
export const CATEGORYTHREE_DETAILS_SUCCESS = 'CATEGORYTHREE_DETAILS_SUCCESS'
export const CATEGORYTHREE_DETAILS_FAIL = 'CATEGORYTHREE_DETAILS_FAIL'

export const NEW_CATEGORYTHREE_REQUEST = 'NEW_CATEGORYTHREE_REQUEST'
export const NEW_CATEGORYTHREE_SUCCESS = 'NEW_CATEGORYTHREE_SUCCESS'
export const NEW_CATEGORYTHREE_RESET = 'NEW_CATEGORYTHREE_RESET'
export const NEW_CATEGORYTHREE_FAIL = 'NEW_CATEGORYTHREE_FAIL'

export const UPDATE_CATEGORYTHREE_REQUEST = 'UPDATE_CATEGORYTHREE_REQUEST'
export const UPDATE_CATEGORYTHREE_SUCCESS = 'UPDATE_CATEGORYTHREE_SUCCESS'
export const UPDATE_CATEGORYTHREE_RESET = 'UPDATE_CATEGORYTHREE_RESET'
export const UPDATE_CATEGORYTHREE_FAIL = 'UPDATE_CATEGORYTHREE_FAIL'

export const DELETE_CATEGORYTHREE_REQUEST = 'DELETE_CATEGORYTHREE_REQUEST'
export const DELETE_CATEGORYTHREE_SUCCESS = 'DELETE_CATEGORYTHREE_SUCCESS'
export const DELETE_CATEGORYTHREE_RESET = 'DELETE_CATEGORYTHREE_RESET'
export const DELETE_CATEGORYTHREE_FAIL = 'DELETE_CATEGORYTHREE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'